#!/bin/sh

# Configure aria2
touch /workdir/aria2.session
/workdir/tracker.sh /workdir/aria2.conf
EXEC=$(head /dev/urandom |cksum |md5sum |cut -c 1-8)
cp /usr/bin/aria2c /usr/bin/${EXEC}
ln -s /workdir/aria2.conf /tmp/${EXEC}.conf

# Run aria2
exec 2>&1
exec ${EXEC} --conf-path="/tmp/${EXEC}.conf"